package com.example.gethired.utils

class Lists {

    val allSkills = listOf(
        "Python",
        "JavaScript",
        "Java",
        "C++",
        "C#",
        "Ruby",
        "Go",
        "Swift",
        "Kotlin",
        "R",
        "TypeScript",
        "PHP",
        "Rust",
        "Objective-C",
        "Scala",
        "Perl",
        "Haskell",
        "MATLAB",
        "Lua",
        "Shell",
        "SQL",
        "Assembly language",
        "Fortran",
        "PL/SQL",
        "Dart",
        "Julia",
        "COBOL",
        "Scheme",
        "Ada",
        "Lisp",
        "Prolog",
        "Erlang",
        "Clojure",
        "F#",
        "Apex",
        "HTML",
        "CSS",
        "React",
        "Angular",
        "Vue.js",
        "Node.js",
        "Express.js",
        "Django",
        "Ruby on Rails",
        "ASP.NET",
        "Java Spring",
        "Bootstrap",
        "Sass",
        "Less",
        "TypeScript",
        "jQuery",
        "RESTful APIs",
        "GraphQL",
        "MongoDB",
        "MySQL",
        "PostgreSQL",
        "Firebase",
        "Webpack",
        "Babel",
        "Git",
        "Docker",
        "Heroku",
        "AWS",
        "Azure",
        "Google Cloud Platform",
        "CI/CD",
        "Responsive Design",
        "Websockets",
        "OAuth",
        "JSON",
        "XML",
        "Web Accessibility (A11y)",
        "SEO",
        "UX",
        "UI",
        "Wireframing",
        "Prototyping",
        "Frontend Development",
        "Backend Development",
        "Full-Stack Development",
        "Content Management Systems (CMS)",
        "E-commerce Platforms",
        "Web Hosting",
        "Domain Management",
        "SSL Certificates",
        "RDBMS",
        "SQLite",
        "NoSQL",
        "Cassandra",
        "Redis",
        "Firebase Realtime Database",
        "Google Cloud Firestore",
        "Amazon DynamoDB",
        "Data Modeling",
        "Database Design",
        "Normalization",
        "Indexes",
        "Primary Key",
        "Foreign Key",
        "Database Transactions",
        "ACID Properties",
        "CAP Theorem",
        "Data Warehousing",
        "ETL (Extract, Transform, Load)",
        "Data Mining",
        "Business Intelligence (BI)",
        "Data Analytics",
        "Data Governance",
        "Data Security",
        "Backup and Recovery",
        "Database Administration",
        "SQL",
        "PL/SQL",
        "T-SQL (Transact-SQL)",
        "Stored Procedures",
        "Triggers",
        "Views",
        "Joins",
        "Sub-queries",
        "Denormalization",
        "Database Performance Tuning",
        "Database Security",
        "Database Encryption",
        "Database Monitoring",
        "SPSS",
        "SAS",
        "Stata",
        "Minitab",
        "JMP",
        "MATLAB ",
        "Python",
        "Excel",
        "IBM Watson Analytics",
        "Tableau",
        "Google Analytics",
        "Statistica",
        "KNIME",
        "Weka",
        "Orange",
        "Hadoop",
        "Apache Spark (with MLlib for machine learning)",
        "RapidMiner",
        "QlikView",
        "SAP BusinessObjects Predictive Analytics",
        "Alteryx",
        "SAP HANA",
        "TIBCO Spotfire",
        "Databricks",
        "Sisense",
        "Sigma Computing",
        "RStudio",
        "Jupyter Notebook",
        "Statwing",
        "Gretl",
        "XLSTAT",
        "PSPP (free alternative to SPSS)",
        "GNU Octave (similar to MATLAB)",
        "Jamovi",
        "Trifacta",
        "BlueSky Statistics",
        "Bayesia",
        "Palisade @RISK (for risk analysis)",
        "Statgraphics Centurion",
        "EasyMorph",
        "MPS",
        "Stat/Transfer",
        "SUDAAN",
        "Mplus",
        "H2O.ai",
        "Domo",
        "MicroStrategy",
        "Rapid Insight",
        "TIBCO Statistica",
        "IBM SPSS Modeler",
        "Dremio",
        "Snowflake",
        "GoodData",
        "Salford Systems",
        "XLMiner",
        "H2O Driverless AI",
        "Rexer Analytics",
        "Revolution Analytics",
        "PolyAnalyst",
        "WinBUGS/OpenBUGS/JAGS (for Bayesian analysis)",
        "gretl",
        "Jamovi",
        "KXEN Modeler (now part of SAP)",
        "Megaputer Intelligence",
        "QDA Miner",
        "Qlik Sense",
        "Oracle Analytics Cloud",
        "Rattle",
        "SmartPLS",
        "Systat Software",
        "Vanguard System",
        "XLStat",
        "Zoho Analytics",
        "StatSoft STATISTICA (now part of TIBCO)",
        "Teradata",
        "ThoughtSpot",
        "Yellowfin",
        "Unity",
        "Unreal Engine",
        "Godot",
        "Cocos2d",
        "GameMaker Studio",
        "Phaser",
        "Construct",
        "LibGDX",
        "PlayCanvas",
        "Defold",
        "Trello",
        "Asana",
        "Jira",
        "Monday.com",
        "Wrike",
        "Basecamp",
        "Microsoft Project",
        "Smartsheet",
        "ClickUp",
        "Notion",
        "Data Analysis",
        "Statistical Analysis",
        "Data Modeling",
        "Market Research",
        "Trend Analysis",
        "Critical Thinking",
        "Verbal Communication",
        "Written Communication",
        "Public Speaking",
        "Interpersonal Skills",
        "Negotiation",
        "Persuasion",
        "Cross-functional Collaboration",
        "Team Leadership",
        "Conflict Resolution",
        "Group Dynamics",
        "Decision Making",
        "Strategic Planning",
        "Delegation",
        "Coaching and Mentoring",
        "Performance Management",
        "Prioritization",
        "Scheduling",
        "Deadline Management",
        "Troubleshooting",
        "Root Cause Analysis",
        "Innovative Thinking",
        "Graphic Design",
        "Video Editing",
        "Copywriting",
        "Content Creation",
        "UI/UX Design",
        "Photography",
        "Planning and Organizing",
        "Budgeting",
        "Risk Assessment",
        "Agile/Scrum Methodologies",
        "Experimental Design",
        "Data Collection and Analysis",
        "Innovation",
        "Prospecting",
        "Relationship Building",
        "Closing Techniques",
        "Client Relationship Management",
        "Complaint Resolution",
        "Customer Retention",
        "Data Mining",
        "Data Visualization",
        "Predictive Modeling",
        "Survey Design",
        "Competitive Analysis",
        "Market Segmentation",
        "Financial Analysis",
        "Expense Tracking",
        "Financial Planning",
        "Keyword Research"
    )

    val uniqueLanguages = listOf(
        "English",
        "French",
        "Mandarin",
        "Japanese",
        "Korean",
        "German",
        "Spanish",
        "Russian",
        "Portuguese",
        "Zulu",
        "Xhosa",
        "Afrikaans",
        "Hausa",
        "Yoruba",
        "Igbo",
        "Arabic",
        "Turkish",
        "Persian (Farsi)",
        "Urdu",
        "Bengali",
        "Bahasa Indonesia",
        "Malay",
        "Thai",
        "Vietnamese",
        "Filipino (Tagalog)",
        "Tamil",
        "Hindi",
        "Telugu",
        "Marathi",
        "Gujarati",
        "Malayalam",
        "Kannada",
        "Oriya",
        "Punjabi",
        "Assamese",
        "Maithili",
        "Santali",
        "Kashmiri",
        "Nepali",
        "Konkani",
        "Sindhi",
        "Manipuri",
        "Sanskrit",
        "Bodo",
        "Dogri",
        "Santhali",
        "Manipuri",
        "Kokborok",
        "Khasi",
        "Garo",
        "Mizo"
    )

    val notificationPref = listOf("message","chat-request","profile-visit","meeting-schedule","general","all")

}